name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.mn120 }}
          password: ${{ secrets.IucipZa2Zg74 }}
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
          repository: ${{ mn120/3120-project4 }}
=======
          repository: ${{ env.mn120/3120-project4 }}
>>>>>>> parent of 52bf235 (Delete docker-image0.yml)
=======
          repository: ${{ env.mn120/3120-project4 }}
>>>>>>> parent of 52bf235 (Delete docker-image0.yml)
=======
          repository: ${{ env.mn120/3120-project4 }}
>>>>>>> parent of 52bf235 (Delete docker-image0.yml)
          tag_with_ref: true
